import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image } from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Play, Pause, ExternalLink, User, Headphones } from 'lucide-react-native';
import { useState } from 'react';

export default function PodcastScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  const [isPlaying, setIsPlaying] = useState(false);

  const {
    title,
    originalTitle,
    description,
    originalDescription,
    imageUrl,
    duration,
    originalUrl,
    person,
    source,
    publishedAt,
  } = params;

  const togglePlayback = () => {
    setIsPlaying(!isPlaying);
    // In a real app, this would control actual audio playback
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <ArrowLeft size={24} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Podcast Comparison</Text>
      </View>

      <ScrollView style={styles.content}>
        {/* AI Generated Podcast Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <View style={styles.aiLabelContainer}>
              <Headphones size={16} color="#fff" />
              <Text style={styles.aiSectionLabel}>AI Generated by {person}</Text>
            </View>
          </View>
          
          <View style={styles.podcastCard}>
            <Image
              source={{ uri: imageUrl as string }}
              style={styles.podcastImage}
            />
            <View style={styles.podcastContent}>
              <Text style={styles.podcastTitle}>{title}</Text>
              <View style={styles.podcastMeta}>
                <View style={styles.metaItem}>
                  <User size={14} color="#666" />
                  <Text style={styles.metaText}>{person}</Text>
                </View>
                <Text style={styles.metaText}>{duration} • {publishedAt}</Text>
              </View>
              <Text style={styles.podcastDescription}>{description}</Text>
              
              <View style={styles.playerContainer}>
                <TouchableOpacity
                  style={styles.playButton}
                  onPress={togglePlayback}
                >
                  {isPlaying ? (
                    <Pause size={24} color="#fff" fill="#fff" />
                  ) : (
                    <Play size={24} color="#fff" fill="#fff" />
                  )}
                </TouchableOpacity>
                <View style={styles.progressContainer}>
                  <View style={styles.progressBar}>
                    <View style={[styles.progressFill, { width: isPlaying ? '30%' : '0%' }]} />
                  </View>
                  <Text style={styles.progressText}>
                    {isPlaying ? '4:32' : '0:00'} / {duration}
                  </Text>
                </View>
              </View>

              <View style={styles.fullPodcastContainer}>
                <Text style={styles.fullPodcastTitle}>Full AI Podcast Transcript</Text>
                <Text style={styles.fullPodcastContent}>
                  {generateFullPodcastTranscript(person as string, title as string, description as string)}
                </Text>
              </View>
            </View>
          </View>
        </View>

        {/* Divider */}
        <View style={styles.divider}>
          <Text style={styles.dividerText}>Original Podcast Below</Text>
        </View>

        {/* Original Podcast Section */}
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <View style={styles.originalLabelContainer}>
              <ExternalLink size={16} color="#fff" />
              <Text style={styles.originalSectionLabel}>Original Source: {source}</Text>
            </View>
          </View>
          
          <View style={styles.podcastCard}>
            <View style={styles.podcastContent}>
              <Text style={styles.podcastTitle}>{originalTitle}</Text>
              <View style={styles.podcastMeta}>
                <View style={styles.metaItem}>
                  <ExternalLink size={14} color="#666" />
                  <Text style={styles.metaText}>{source}</Text>
                </View>
                <Text style={styles.metaText}>{publishedAt}</Text>
              </View>
              <Text style={styles.podcastDescription}>{originalDescription}</Text>
              
              <TouchableOpacity
                style={styles.listenOriginalButton}
                onPress={() => {
                  // In a real app, you would open the original podcast URL
                }}
              >
                <ExternalLink size={16} color="#fff" />
                <Text style={styles.listenOriginalButtonText}>Listen to Original Podcast</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>

        {/* Audio Player Placeholder for Original */}
        <View style={styles.audioPlayerContainer}>
          <Text style={styles.audioPlayerTitle}>Original Podcast Player</Text>
          <View style={styles.audioPlayerPlaceholder}>
            <Headphones size={48} color="#ccc" />
            <Text style={styles.audioPlayerPlaceholderText}>
              In a production app, this would embed the original podcast audio player
            </Text>
            <Text style={styles.audioPlayerUrl}>{originalUrl}</Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

function generateFullPodcastTranscript(person: string, title: string, description: string): string {
  const transcriptTemplates = {
    'Albert Einstein': `
HOST: Today we're joined by the brilliant mind of Albert Einstein. Professor, thank you for being with us.

EINSTEIN: The pleasure is mine. I find great joy in exploring ideas and sharing the wonder of scientific discovery.

HOST: Let's dive into today's topic. What are your thoughts on this development?

EINSTEIN: You know, when I observe the complexities of our modern world, I'm reminded of the fundamental principles that govern all existence. ${description}

What fascinates me most is how seemingly unrelated phenomena often reveal deep connections. It's like my work with relativity - time and space, which appeared separate, are actually interwoven in the fabric of spacetime.

HOST: That's a beautiful way to think about it. How do you see this affecting humanity's future?

EINSTEIN: The future belongs to those who maintain their curiosity and continue to ask questions. As I've often said, the important thing is not to stop questioning. In this situation, we must ask not just what is happening, but why it's happening and what it means for our understanding of the world.

I believe that our role as human beings is to expand the circle of our compassion and understanding. This development, like all human endeavors, should be measured not just by its immediate impact, but by how it contributes to the greater good of humanity.

HOST: Any final thoughts for our listeners?

EINSTEIN: Remember that imagination is more important than knowledge. Knowledge is limited, but imagination embraces the entire world, stimulating progress and giving birth to evolution. Let us approach these challenges with both scientific rigor and creative thinking.
    `,
    'Oprah Winfrey': `
OPRAH: Hello, beautiful souls! Welcome back to our conversation about what really matters. Today I want to talk to you about something that's been on my heart and mind.

${description} And what I know for sure is that behind every story, every headline, every development, there are real people with real feelings, real dreams, and real struggles.

I've been thinking about this a lot lately, and I keep coming back to one of my favorite quotes: "The greatest discovery of all time is that a person can change their future by merely changing their attitude toward it."

You know, I've had the privilege of talking to thousands of people over the years, and what I've learned is that our stories connect us. When we share our truth, when we're vulnerable and authentic, we create space for others to do the same.

This situation we're discussing today - it's not just about facts and figures. It's about the human experience. It's about how we show up for each other in times of challenge and uncertainty.

What moves me most is the resilience I see in people. Time and time again, I witness ordinary people doing extraordinary things. They find strength they didn't know they had, they discover purpose in their pain, and they choose hope over fear.

That's what I want to leave you with today. Whatever you're facing, whatever challenges seem insurmountable, remember that you have within you everything you need to not just survive, but to thrive.

Your story matters. Your voice matters. And the world needs what you have to offer. So let's keep lifting each other up, one conversation at a time.

Much love to you all. We'll be right back after this.
    `,
    'Elon Musk': `
HOST: Elon, thanks for joining us. I know you're incredibly busy with your various ventures.

ELON: Thanks for having me. Always happy to discuss how we can solve important problems and make the future better.

HOST: So what's your take on this latest development?

ELON: Look, I think we need to approach this from first principles. What are we actually trying to solve here? ${description}

The thing is, most people optimize for the wrong variables. They focus on incremental improvements when what we really need is a fundamental rethink of the entire system.

HOST: Can you elaborate on that?

ELON: Sure. Think about it this way - if you're trying to make a car 10% better, you might improve the engine efficiency. But if you want to make it 10 times better, you need to question whether you even need an engine at all. Maybe the answer is electric motors, or maybe it's something we haven't even thought of yet.

The same principle applies here. We can't just accept the status quo as a given. We need to ask: what would this look like if we designed it from scratch today, with all the tools and knowledge we have available?

HOST: What role do you think technology plays in solving these challenges?

ELON: Technology is just a tool. The real question is: are we using it to solve the right problems? I'm optimistic about the future because I believe human ingenuity, combined with rapidly advancing technology, can solve almost any problem.

But we need to maintain a sense of urgency. The future is not predetermined - it's something we actively create through our choices and actions today.

The key is to think big, move fast, and be willing to fail and iterate. That's how we make progress.

HOST: Any final thoughts?

ELON: Just that the future is going to be wild, and we all have a role to play in making it awesome. Let's build something great together.
    `,
    'Default': `
HOST: Thank you for joining us today. This is certainly a topic that's capturing attention across many sectors.

GUEST: Thank you for having me. It's important that we have these conversations and examine these developments from multiple angles.

HOST: What do you think is the most significant aspect of this story?

GUEST: ${description} I think what's particularly noteworthy is how this reflects broader trends we're seeing across society.

These kinds of developments don't happen in isolation. They're part of a larger tapestry of social, economic, and technological changes that are reshaping how we live and work.

HOST: How do you see this playing out in the long term?

GUEST: Well, I think we're still in the early stages of understanding the full implications. What's clear is that we need to be thoughtful about how we respond and adapt.

The most successful individuals and organizations will be those that can remain flexible and responsive to changing circumstances while staying true to their core values and mission.

HOST: What advice would you give to people who are trying to navigate these changes?

GUEST: I'd say the key is to stay informed but not overwhelmed. Focus on what you can control and influence, rather than getting caught up in things beyond your reach.

It's also important to maintain perspective. While these changes feel significant - and they are - humans have always been remarkably adaptable. We've faced challenges before and found ways to thrive.

HOST: Thank you for sharing your insights with us today.

GUEST: My pleasure. Thank you for the thoughtful conversation.
    `
  };

  return transcriptTemplates[person as keyof typeof transcriptTemplates] || transcriptTemplates.Default;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    backgroundColor: '#1E3A8A',
    paddingTop: 60,
    paddingBottom: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    marginRight: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  content: {
    flex: 1,
  },
  section: {
    padding: 16,
  },
  sectionHeader: {
    marginBottom: 16,
  },
  aiLabelContainer: {
    backgroundColor: '#9C27B0',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  aiSectionLabel: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  originalLabelContainer: {
    backgroundColor: '#1E3A8A',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  originalSectionLabel: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  podcastCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  podcastImage: {
    width: '100%',
    height: 200,
    backgroundColor: '#f0f0f0',
  },
  podcastContent: {
    padding: 20,
  },
  podcastTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 12,
    lineHeight: 28,
  },
  podcastMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 4,
  },
  podcastDescription: {
    fontSize: 16,
    color: '#666',
    lineHeight: 24,
    marginBottom: 20,
  },
  playerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  playButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#9C27B0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  progressContainer: {
    flex: 1,
  },
  progressBar: {
    height: 4,
    backgroundColor: '#e9ecef',
    borderRadius: 2,
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#9C27B0',
    borderRadius: 2,
  },
  progressText: {
    fontSize: 12,
    color: '#666',
  },
  fullPodcastContainer: {
    borderTopWidth: 1,
    borderTopColor: '#e9ecef',
    paddingTop: 20,
  },
  fullPodcastTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 12,
  },
  fullPodcastContent: {
    fontSize: 16,
    color: '#333',
    lineHeight: 26,
    fontFamily: 'monospace',
  },
  divider: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  dividerText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
    backgroundColor: '#f8f9fa',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#e9ecef',
  },
  listenOriginalButton: {
    backgroundColor: '#1E3A8A',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  listenOriginalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  audioPlayerContainer: {
    margin: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  audioPlayerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 16,
    textAlign: 'center',
  },
  audioPlayerPlaceholder: {
    alignItems: 'center',
    padding: 40,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e9ecef',
    borderStyle: 'dashed',
  },
  audioPlayerPlaceholderText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginVertical: 16,
    lineHeight: 22,
  },
  audioPlayerUrl: {
    fontSize: 12,
    color: '#999',
    textAlign: 'center',
  },
});